image: Ubuntu1804  # образ для сборки
stack: jdk 11
branches:
  only:
    - master  # ветка git
build: off  # будем использовать свой скрипт сборки

services:
  - docker # будем использовать сервис для работы
  
install:  
  
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - ps: sudo curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
  - ps: sudo bash nodesource_setup.sh
  - ps: sudo apt install nodejs
  - npm start --prefix ./gate-simulator &
  - sleep 10
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar &

test_script:
  - chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме

build_script:
  - sleep 10
  - sudo chmod +x ./gradlew
  # - ./gradlew test -Dselenide.headless=true -Durlbd=jdbc:mysql://localhost:3306/app
  - ./gradlew test -Ddb.url=jdbc:mysql://localhost:3306/app -Ddb.user=app -Ddb.password=pass
