image: Ubuntu1804  # образ для сборки
stack: jdk 11
branches:
  only:
    - master  # ветка git
build: off  # будем использовать свой скрипт сборки

services:
  - docker # будем использовать сервис для работы
install:  
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - ps: sudo curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
  - ps: sudo bash nodesource_setup.sh
  - ps: sudo apt install nodejs
  - ps: sudo cd gate-simulator
  - ps: sudo npm start
  - sleep 10
  - ps: java -D spring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar &

test_script:
  - ps: cd gate-simulator
  - npm start
  - ps: chmod +x gradlew
  - ps: ./gradlew test --info "-D selenide.headless=true"  # стартуем Selenide в Headless-режиме

build_script:
  - sleep 10
  - ps: sudo chmod +x ./gradlew
  - ps: ./gradlew test -D selenide.headless=true -D url=jdbc:mysql://localhost:3306/app
